language: scala
scala:
  - 2.11.11
jdk:
  - oraclejdk8

env:
  global:
    - secure: "Qe/AE3NndwXjGTWnJMrt41JYEijxgFNRd3eakjXE2RThMRANx/sUeJYbDYBXLpeoDOQtkVfU7VQ81mgWimD7CKqHA9qWMnP/QXYBWwNn7SIVgHWvYOnJe9LS2YW+4Oq8AKKIDVpO50r298S2e2Axcc0OLNAQanHXW96p/mjFpXm/JBr+4j6oRfOCcCwkfRh2Fe02nWQXz2ilu1INGXonZ/kgJ06VUItXjElm43JixuWTGbjGoVDQnXLdcN5+yQ3/Lo3zM5CcK1s92aDafZ6vqQoTvGCCQnDtZwU+yB80SMvaGa27Bxc3nmL2OH6L+rud4ovSl4Uf4LHR1jSZW/IrMfv1VHyuDmnUvXs1Ti8CTZ04s6FxtVrEWmnuNFrQIBcBOnAjdjGs2n5/zx2WrnDd+l8ldh9HavEf7AjOCpWie1sf2cRDSllPm270dh5Ws/MRDpLDl+E/eqP73N81TFyGztoaR2v65Cw2Og/hphTfPbEMy2GQGP1jBPYuHQVwR5tqTf6lGPcygjFek5ztiLzv+/ZRcJntnYvnOoK1d+6F1jAjLSElp+YPF5bnte7wHkVem8kg+ZgGrCx/kD+pQckuhpEyddXDvkoVdXUDS1uTvs/f8PjATghGszO7LCvdEmfZPLRmACqIkqn1jD5JcS/3Xmcw4Xfa3EtzWIF+phy+3BI="

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

script:
  - sbt ++$TRAVIS_SCALA_VERSION scalastyle scapegoat coverage test doc coverageReport

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

after_success:
  - sbt coveralls
